// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Authentication.Models;

public partial class AspNetOrder
{
    public int Id { get; set; }

    public DateTime Date { get; set; }

    public string Status { get; set; }

    public string CustomerId { get; set; }

    public double Value { get; set; }
}